### ISSUE TITLE
the query result print so slow

### ISSUE THREAD

**Issue by sukeyisme** [sebasmonia/sqlcmdline#3]
50 rows and 150 cols need half a minute

**Comment by sebasmonia** [comment]
One improvement would be to make one single call to print instead of one print per row. There's a trade-off though as that means we would build a gigantic string first with all the results concatenated by \n.

I began exploring the idea of sending results to a CSV instead of printing, to better handle bigger output.
I'm open to other suggestions too.

If you don't mind, under which OS are you running the script? Are you using the terminal or some other tool?

Thanks you,
Sebastian

**Comment by sukeyisme** [comment]
osx

**Comment by sebasmonia** [comment]
Commit https://github.com/sebasmonia/sqlcmdline/commit/d58cae0c08638850bb442c4a428b24a62421f786 attemps to fix this.

**Comment by sukeyisme** [comment]
I use in emacs ,still slow .

**Comment by sebasmonia** [comment]
All the iterations to determine the column widths are probably the biggest time sink now. Will profile the script to confirm.

**Comment by sebasmonia** [comment]
Turns out the call to cursor.nextset() is incredibly slow. But I don't know why, and can't find anyone with a similar issue.

**Comment by sebasmonia** [comment]
Tried to add support for turbodbc but it is 64 bit only. The latest version of pypyodbc has an error when creating the connection (might be related to having 32bit python).

Until I can update my installation to 64 bit, I can't test these alternatives to pyodbc.

**Comment by sebasmonia** [comment]
@sukeyisme still experiencing slow printing?
