### ISSUE TITLE
GO

### ISSUE THREAD

**Issue by sukeyisme** [sebasmonia/sqlcmdline#4]
Does it can use ';' to query data?

**Comment by sebasmonia** [comment]
Hi,

I had that feature for a few days but didn't think it was too useful. It required ";" instead of "GO"  in the last line, saving just one char.

I was thinking maybe having ";" at the end of the query could execute it immediately. But I didn't check the T-SQL standard to understand if I was clashing with it.

Let me check that a bit.

**Comment by sukeyisme** [comment]
ok，thanks for your good tools.

**Comment by sebasmonia** [comment]
As per https://stackoverflow.com/questions/710683/when-should-i-use-semicolons-in-sql-server semicolons are valid syntax and actually will be required.

Would it make sense to use "!"?
>SELECT * FROM some_table!
would be equivalent to
>SELECT * FROM some_table
>GO

Saves some typing for interactive queries, especially one liners.
Thoughts?

**Comment by sukeyisme** [comment]
I think you're right, saving just one char. I close the issues

**Comment by sebasmonia** [comment]
I tested ! for a couple days. Not very comfortable.

But I figure ;; (double semi colon) could be better (this only applies to the interactive mode, not external files).

You would type "SELECT * FROM some_table;;" and SQL Server would receive "SELECT * FROM some_table;"

Will test and let you know.
